# Generated by Django 5.1.7 on 2025-03-17 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_enquiry_industry_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='industries'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
        migrations.CreateModel(
            name='DisplayProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_products', models.ManyToManyField(blank=True, related_name='display_hide_products', to='myapp.product')),
                ('show_products', models.ManyToManyField(blank=True, related_name='display_show_products', to='myapp.product')),
            ],
        ),
    ]
