# Generated by Django 5.1.7 on 2025-03-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_industry_image_alter_quote_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(default=None)),
                ('add_url', models.TextField(default=None)),
                ('phone1', models.CharField(blank=True, default=None, max_length=15)),
                ('phone2', models.CharField(blank=True, default=None, max_length=15)),
                ('urgent_phone', models.CharField(blank=True, default=None, max_length=15)),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
                ('business_hours', models.TextField(default=None)),
            ],
        ),
    ]
