# Generated by Django 5.1.7 on 2025-03-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='facebook',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkdin',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='twitter',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='business_hours',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone1',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone2',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='contact',
            name='urgent_phone',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
