# Generated by Django 5.1.7 on 2025-03-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_certificate_alter_contact_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTUdyamCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst', models.FileField(upload_to='certificates')),
                ('udyam', models.FileField(upload_to='certificates')),
                ('is_show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ISOCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='certificates')),
            ],
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
