# Generated by Django 5.1.7 on 2025-03-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_gstudyamcertificate_isocertificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iso1', models.FileField(upload_to='certificates')),
                ('iso2', models.FileField(upload_to='certificates')),
                ('iso3', models.FileField(upload_to='certificates')),
                ('gst', models.FileField(upload_to='certificates')),
                ('udyam', models.FileField(upload_to='certificates')),
            ],
        ),
    ]
